# Generated by Django 4.2.13 on 2024-07-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("urlshort", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=10)),
                ("img", models.ImageField(upload_to="qrcodes")),
                ("url", models.URLField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name="url",
            name="url",
            field=models.URLField(max_length=10000),
        ),
    ]
